spring.application.name=simplepaymentplatform

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true

external.auth.tool.url=https://util.devi.tools/api/v2/authorize
external.notification.tool.url=https://util.devi.tools/api/v1/notify